version: '2'
services:
  testsuivi-app:
    image: testsuivi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testsuivi-postgresql:5432/testSuivi
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  testsuivi-postgresql:
    extends:
      file: postgresql.yml
      service: testsuivi-postgresql
